from classes.Adocao import Adocao
from classes.Animal import Animal
from classes.Doador import Doador
from classes.Estoque import Estoque
from classes.Item import Item
from classes.Pessoa import Pessoa
from classes.Pretedente import Pretendente
from classes.Resgate import Resgate
from classes.Tratamento import Tratamento
from classes.Voluntario import Voluntario